# Generated by Django 4.2.6 on 2023-10-25 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('manager_email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Manager Email')),
                ('manager_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manager Name')),
                ('manager_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manager Title')),
                ('manager_level', models.CharField(blank=True, max_length=20, null=True, verbose_name='Manager Level')),
                ('manager_level_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manager Level Description')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='org_tree.organizationunit', verbose_name='Parent Unit')),
            ],
            options={
                'verbose_name': 'Organization Unit',
                'verbose_name_plural': 'Organization Units',
                'db_table': 'ORGANIZATION_UNITS',
                'managed': True,
            },
        ),
    ]
